version: '3.1'

services:

  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./data:/data/db:rw
    ports:
      - 27017:27017
    command: ["mongod", "--auth"]

  mongo-init:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: admin
    command: >
      mongo admin
      --host mongo
      -u root -p 123456
      --eval "db.createUser({user: 'shadman', pwd: '12345678', roles: [{role: 'readWriteAnyDatabase', db: 'admin'}]})"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/